[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
  path = "/api/games"
  function = "cache-games"

[dev]
  command = "npm run dev"
  port = 4321
  
[[redirects]]
  from = "/api/games/*"
  to = "/.netlify/edge-functions/cache-games"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"